platform :ios, '9.0'

target 'SPComponentExample' do
  use_frameworks!

  # Pods for SPComponentExample
  pod 'SPComponent', :path => '../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'SPComponentExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
